-- 全平台智能记账应用 - 数据库初始化脚本
-- PostgreSQL

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(50),
    avatar_url VARCHAR(255),
    phone VARCHAR(20),
    status INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 账本表
CREATE TABLE IF NOT EXISTS books (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(50),
    color VARCHAR(20),
    type INTEGER DEFAULT 1,
    is_default INTEGER DEFAULT 0,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 分类表
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY,
    book_id BIGINT NOT NULL,
    parent_id BIGINT DEFAULT 0,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(50),
    type INTEGER NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 账户表
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    type INTEGER NOT NULL,
    balance DECIMAL(15,2) DEFAULT 0.00,
    currency VARCHAR(10) DEFAULT 'CNY',
    icon VARCHAR(50),
    color VARCHAR(20),
    is_include BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 交易记录表
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT PRIMARY KEY,
    book_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    type INTEGER NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR(255),
    location VARCHAR(100),
    merchant VARCHAR(100),
    tags VARCHAR(255),
    attachment_urls TEXT,
    is_transfer BOOLEAN DEFAULT false,
    transfer_to_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 预算表
CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT,
    category_id BIGINT,
    amount DECIMAL(15,2) NOT NULL,
    budget_type INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    warning_threshold DECIMAL(5,2) DEFAULT 80.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 导出记录表
CREATE TABLE IF NOT EXISTS export_record (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    book_id BIGINT,
    export_type VARCHAR(50) NOT NULL,
    file_format VARCHAR(20) NOT NULL,
    file_path TEXT,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    error_message TEXT,
    expire_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 通知记录表
CREATE TABLE IF NOT EXISTS notification (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    type INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    template_id BIGINT,
    status INTEGER NOT NULL DEFAULT 1,
    error_message TEXT,
    sent_at TIMESTAMP,
    read_at TIMESTAMP,
    biz_type VARCHAR(50),
    biz_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 通知模板表
CREATE TABLE IF NOT EXISTS notification_template (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL,
    type INTEGER NOT NULL,
    content TEXT NOT NULL,
    title_template VARCHAR(255),
    biz_type VARCHAR(50),
    is_enabled INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

-- 用户通知偏好表
CREATE TABLE IF NOT EXISTS user_notification_preference (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    book_id BIGINT,
    email_enabled INTEGER DEFAULT 0,
    sms_enabled INTEGER DEFAULT 0,
    in_app_enabled INTEGER DEFAULT 1,
    push_enabled INTEGER DEFAULT 1,
    subscribed_types TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    UNIQUE(user_id, book_id)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_books_user_id ON books(user_id);
CREATE INDEX IF NOT EXISTS idx_categories_book_id ON categories(book_id);
CREATE INDEX IF NOT EXISTS idx_accounts_user_id ON accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_book_id ON transactions(book_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(transaction_date);
CREATE INDEX IF NOT EXISTS idx_budgets_user_id ON budgets(user_id);
CREATE INDEX IF NOT EXISTS idx_export_record_user_id ON export_record(user_id);
CREATE INDEX IF NOT EXISTS idx_export_record_book_id ON export_record(book_id);
CREATE INDEX IF NOT EXISTS idx_export_record_status ON export_record(status);
CREATE INDEX IF NOT EXISTS idx_notification_user_id ON notification(user_id);
CREATE INDEX IF NOT EXISTS idx_notification_status ON notification(status);
CREATE INDEX IF NOT EXISTS idx_notification_template_code ON notification_template(code);
CREATE INDEX IF NOT EXISTS idx_user_preference_user_id ON user_notification_preference(user_id);

-- 插入默认通知模板数据
INSERT INTO notification_template (name, code, type, content, title_template, biz_type, is_enabled) VALUES
('预算预警', 'BUDGET_ALERT', 3, '预算"{budgetName}"已达到{progress}%，请注意控制支出。', '预算预警', 'budget', 1),
('预算超支', 'BUDGET_OVERDUE', 3, '预算"{budgetName}"已超支（{progress}%），请及时调整预算。', '预算超支', 'budget', 1),
('周期账单执行', 'RECURRING_BILL_EXECUTED', 3, '周期账单"{billName}"已执行，金额：{amount}元。', '周期账单执行', 'recurring', 1),
('储蓄目标完成', 'SAVINGS_COMPLETED', 3, '恭喜！储蓄目标"{targetName}"已完成，已存{amount}元。', '储蓄目标完成', 'savings', 1);

-- 插入默认数据（可选）
-- INSERT INTO users (id, username, email, password_hash, nickname) VALUES 
-- (1, 'admin', 'admin@example.com', '$2a$10$...', '管理员');
